name: Unit & Integration Tests
on:
  pull_request:
    branches: [main, stage]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i
      - name: Unit & Integration Tests
        run: npm run test:ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report.html
          path: reports/test-report.html
          retention-days: 30
